version: '3.8'

services: 
  web: 
    container_name: cocktails-web-cmp-local
    build:
      dockerfile: './Dockerfile'
      context: './cocktails.frontend/cocktails.web'
    image: cocktails-web:local
    ports:
      - '3000:80'
      - '3001:443'
    environment:
      - VITE_NODE_ENV=production
      - VITE_PORT=3000
      - VITE_REDIRECT_URI=http://localhost:3000/
      - VITE_INSTRUMENTATION_KEY=044ef31e-de88-4a3b-8ded-a9b635a91ee6
      - VITE_B2C_TENANT=cezzis
      - VITE_B2C_CLIENT_ID=84744194-da27-410f-ae0e-74f5589d4c96
      - VITE_B2C_POLICY=B2C_1_SignInSignUp_Policy
      - VITE_COCKTAILS_API_URL=https://localhost:6001
      - VITE_COCKTAILS_APIM_SUBSCRIPTION_KEY=383hudiudhUJK984jdus7HDY

  api: 
    container_name: cocktails-api-cmp-local
    build:
      dockerfile: './cocktails.api/src/Cocktails.Api/Dockerfile'
    image: cocktails-api:local
    ports:
      - '6000:8080'
      - '6001:8081'
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  func: 
    container_name: cocktails-func-cmp-local
    build:
      dockerfile: './cocktails.backend/src/Cocktails.Backend/Dockerfile'
    image: cocktails-func:local
    ports:
      - '9000:8080'
      - '9001:8081'
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro

# Run from the root of the repo
# docker-compose --file ./Docker-Compose.yml up -d