name: cicd-cezzis-nuget

on:
  pull_request:
    branches: [main]
    paths: [cocktails.common/**, .github/workflows/cezzis-nuget-cicd.yaml]
  push:
    branches: [main]
    paths: [cocktails.common/**, .github/workflows/cezzis-nuget-cicd.yaml]

  workflow_dispatch:

jobs:
  nuget-pack-and-push:
    uses: mtnvencenzo/workflows/.github/workflows/nuget-pack-and-push.yaml@main
    with:
      working_directory: 'cocktails.common'
      environment_name: prd
      allow_push: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
      dotnet_version: '9.x'
      nuget_file_path: './../Nuget.Config'
      github_nuget_feed_name: 'github-mtnvencenzo'
      github_nuget_feed_source: 'https://nuget.pkg.github.com/mtnvencenzo/index.json'
      project_path: './Cocktails.Common.sln'
      test_project_path: './Cocktails.Common.sln'
      publish_project_path: './src/Cocktails.Common/Cocktails.Common.csproj'
      artifact_name: 'cocktails-nuget'
      setup_files: '' # Must be a string representation of a json array with items separated by ', '
      publish_directory_name: 'nuget'
    secrets:
      github_packages_pat_token: ${{ secrets.GH_PACKAGES_PAT_TOKEN }}
