name: cicd-cezzis-web

on:
  pull_request:
    branches: [main]
    paths: [cocktails.frontend/**, .github/workflows/cocktails-web-cicd.yaml]
  push:
    branches: [main]
    paths: [cocktails.frontend/**, .github/workflows/cocktails-web-cicd.yaml]

  workflow_dispatch:

jobs:
  build:
    name: Build app
    uses: mtnvencenzo/workflows/.github/workflows/ui-build.yaml@main
    with:
      working_directory: 'cocktails.frontend/cocktails.web'
      node_version: '23.5.x'
      setup_files: '[".env", "env.sh", "nginx-default.conf", "Dockerfile-CI"]' # Must be a string representation of a json array with items separated by ', '
      upload_artifact: true
      artifact_name: 'cocktails-web'
    secrets:
      github_packages_pat_token: ${{ secrets.GH_PACKAGES_PAT_TOKEN }}

  docker:
    name: Containerize app
    needs: [build]
    uses: mtnvencenzo/workflows/.github/workflows/docker-build-and-push.yaml@main
    with:
      working_directory: 'cocktails.frontend/cocktails.web'
      allow_build_and_push: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
      artifact_name: 'cocktails-web'
      docker_file_name: 'Dockerfile-CI'
      image_tag: '${{ github.sha }}'
      acr_registry_login_server: 'acrveceusgloshared001.azurecr.io'
      acr_image_repository: 'cocktailsweb'
    secrets:
      acr_registry_login_username: ${{ secrets.ACR_REGISTRY_USERNAME }}
      acr_registry_login_password: ${{ secrets.ACR_REGISTRY_PASSWORD }}

  terraform_deploy_prd:
    name: Terraform deploy prd
    uses: mtnvencenzo/workflows/.github/workflows/terraform-plan-and-apply.yaml@main
    needs: [docker]
    with:
      working_directory: cocktails.frontend/.deployment/iac/terraform
      environment_name: prd
      allow_deploy: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
      terraform_version: 1.11.4
      arm_client_id: ${{ vars.ARM_CLIENT_ID }}
      arm_subscription_id: ${{ vars.ARM_SUBSCRIPTION_ID }}
      arm_tenant_id: ${{ vars.ARM_TENANT_ID }}
      backend_resource_group_name: rg-vec-eus-administration-001
      backend_storage_account_name: stveceusterraformstat001
      backend_container_name: terraform-cocktails
      backend_blob_key: cocktails/prd-cocktails-web.tfstate
      command_line_args: '-var image_tag=${{ github.sha }}'
    secrets:
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      terraform_module_repo_access_key_secret: ${{ secrets.TERRAFORM_MODULE_REPO_ACCESS_KEY_SECRET }}
      command_line_args: '-var "b2c_terraform_app_registration_client_id=${{ secrets.TERRAFORM_APP_REGISTRATION_CLIENT_ID }}" -var "b2c_terraform_app_registration_client_secret=${{ secrets.TERRAFORM_APP_REGISTRATION_CLIENT_SECRET }}"'
    
  cypress_e2e_prd:
    name: Cypress e2e prd
    uses: mtnvencenzo/workflows/.github/workflows/cypress-runner.yaml@main
    needs: [terraform_deploy_prd]
    with:
      base_url: 'https://www.cezzis.com'
      working_directory: cocktails.frontend/cocktails.web.e2e
      environment_name: prd
      allow_run: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main' }}
      command_line_args: '--env b2cUrl=https://cezzis.b2clogin.com/ --env b2cTenantId=fb512a9c-5b44-41ab-8042-6465769f16c9 --env b2cClientId=84744194-da27-410f-ae0e-74f5589d4c96 --env b2cUserObjectId=41598664-1466-4e3e-b28c-dfe9837e462e --env b2cUserEmail=rvecchi+cypress@gmail.com --env b2cUserPassword='
    secrets:
      cypress_user_password: ${{ secrets.PRD_CYPRESS_USER_PASSWORD }}